version: '3.3'

services:
  backend:
    container_name: backend
    # platform: linux/amd64
    build:
      context: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    env_file:
      - .env

  frontend:
    container_name: frontend
    # platform: linux/amd64
    build:
      context: ./frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules/
