version: '3.3'

services:
  backend:
    container_name: backend
    build: 
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "8080:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
