- apiVersion: v1
  kind: Namespace
  metadata:
    name: default
  spec:
    finalizers:
      - kubernetes
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: gpt-backend
    namespace: default
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: gpt-backend
    template:
      metadata:
        labels:
          app: gpt-backend
      spec:
        nodeSelector:
          kubernetes.io/os: linux
        containers:
          - name: gpt-backend
            image: gptstudentapp.azurecr.io/gpt-backend:latest
            ports:
              - containerPort: 80
- apiVersion: v1
  kind: Service
  metadata:
    name: gpt-backend-service
    namespace: default
  spec:
    type: LoadBalancer
    ports:
      - targetPort: 80
        name: port80
        port: 80
        protocol: TCP
    selector:
      app: gpt-backend
