apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gpt-backend
  template:
    metadata:
      labels:
        app: gpt-backend
    spec:
      containers:
        - name: gpt-backend
          image: gptstudentapp.azurecr.io/gpt-backend:latest
          ports:
            - containerPort: 8000
              name: gunicorn
